"""Self-contained HTML report (zero dependencies) - also the automatic fallback if reportlab is missing."""
from __future__ import annotations

import os
from html import escape as e

from models import ScanResult
from report.scoring import summarize

COL = {"critical": "#7b1fa2", "high": "#d32f2f", "medium": "#f57c00", "low": "#0288d1", "info": "#757575"}


def _badge(sev: str) -> str:
    return '<span class="b" style="background:%s">%s</span>' % (COL.get(sev, "#777"), e(sev.upper()))


def write_html(result: ScanResult, path: str) -> str:
    s = summarize(result)
    h = []
    h.append("""<!doctype html><html><head><meta charset="utf-8"><title>Vulnerability Assessment Report</title>
<style>body{font-family:Segoe UI,Arial,sans-serif;margin:0;background:#f4f6f8;color:#222}
.w{max-width:1100px;margin:auto;padding:24px}h1{margin:0}header{background:#0d1b2a;color:#fff;padding:28px 0}
.card{background:#fff;border-radius:8px;padding:18px;margin:16px 0;box-shadow:0 1px 3px #0002}
.k{display:flex;gap:12px;flex-wrap:wrap}.k div{flex:1;min-width:130px;background:#fff;border-radius:8px;padding:14px;text-align:center;box-shadow:0 1px 3px #0002}
.k b{display:block;font-size:26px}table{border-collapse:collapse;width:100%;font-size:14px}
th,td{border-bottom:1px solid #e3e6ea;padding:7px 8px;text-align:left;vertical-align:top}th{background:#eef1f4}
.b{color:#fff;border-radius:4px;padding:2px 7px;font-size:12px;font-weight:600}code{background:#eef1f4;padding:1px 4px;border-radius:3px}
.mut{color:#666;font-size:13px}</style></head><body>""")
    h.append('<header><div class="w"><h1>Network Vulnerability Assessment</h1><div>Scan %s &middot; %s</div></div></header><div class="w">'
             % (e(result.scan_id), e(result.started)))
    h.append('<div class="card"><b>Targets:</b> %s<br><b>Duration:</b> %.1fs &nbsp; <b>Tool:</b> v%s</div>'
             % (e(result.targets), result.duration_s, e(result.tool_version)))
    h.append('<div class="k"><div><b>%d</b>Hosts</div><div><b>%d</b>Open ports</div><div><b>%d</b>CVEs</div>'
             '<div><b style="color:%s">%d</b>Critical CVEs</div><div><b style="color:%s">%d</b>High CVEs</div></div>'
             % (s["hosts"], s["open_ports"], s["cves"], COL["critical"], s["cve_severity"]["critical"],
                COL["high"], s["cve_severity"]["high"]))
    for host in sorted(result.hosts, key=lambda x: -x.risk_score):
        h.append('<div class="card"><h2>%s %s %s</h2><div class="mut">OS: %s (%s) &middot; Risk score %d/100</div>'
                 % (e(host.ip), ("(%s)" % e(host.hostname)) if host.hostname else "", _badge(host.risk_level),
                    e(host.os_guess), e(host.os_source or "n/a"), host.risk_score))
        if host.ports:
            h.append("<h3>Open ports</h3><table><tr><th>Port</th><th>Service</th><th>Product / Version</th><th>Banner</th></tr>")
            for p in host.ports:
                pv = ("%s %s" % (p.product or "", p.version or "")).strip() or "-"
                h.append("<tr><td>%d/tcp</td><td>%s%s</td><td>%s</td><td><code>%s</code></td></tr>"
                         % (p.port, e(p.service), " (TLS)" if p.tls else "", e(pv), e(p.banner.replace("\n", " ")[:110])))
            h.append("</table>")
            fr = [(p, f) for p in host.ports for f in p.findings if f.severity != "info"]
            if fr:
                h.append("<h3>Findings</h3><table><tr><th>Severity</th><th>Finding</th><th>Remediation</th></tr>")
                for p, f in sorted(fr, key=lambda t: ["critical", "high", "medium", "low", "info"].index(t[1].severity)):
                    h.append("<tr><td>%s</td><td><b>%s</b><br><span class='mut'>%s</span></td><td>%s</td></tr>"
                             % (_badge(f.severity), e(f.title), e(f.detail), e(f.remediation)))
                h.append("</table>")
            vr = [(p, v) for p in host.ports for v in p.vulns]
            if vr:
                h.append("<h3>Known vulnerabilities (CVE)</h3><table><tr><th>CVE</th><th>CVSS</th><th>Port</th><th>Description</th></tr>")
                for p, v in sorted(vr, key=lambda t: -(t[1].cvss or 0)):
                    h.append('<tr><td><a href="%s">%s</a><br><span class="mut">%s</span></td><td>%s %s</td><td>%d</td><td>%s</td></tr>'
                             % (e(v.url), e(v.cve_id), e(v.source), _badge(v.severity),
                                "" if v.cvss is None else "%.1f" % v.cvss, p.port, e(v.description[:300])))
                h.append("</table>")
        else:
            h.append("<p>No open ports found in the scanned range.</p>")
        h.append("</div>")
    h.append('<p class="mut">Generated by VulnScan. Results reflect a point-in-time, non-intrusive assessment; '
             'CVE matches are based on detected versions and may include false positives (e.g. backported patches).</p></div></body></html>')
    with open(path, "w", encoding="utf-8") as f:
        f.write("".join(h))
    return os.path.abspath(path)
